### ISSUE TITLE
Add support for playing audio

### ISSUE THREAD

**Issue by SupremeC** [SupremeC/ControlPanelMasterPy#5]
###Requirements:
+ 1 background channel
+ X number of channels

###TODO:
+ [x] Play audio when ctrl is used
+ [x] Play audio when audioPresetCtrl is used
+ [x] Link analog.pot to volume
